added the first block of the home page
Capsonchik/NFT-Marketplace pull request #16
Opened 2022-08-03 10:00 UTC by Cra7yy

added the first block of the main page has configured the adaptivity so far works as in the old project

2022-08-04 08:15 UTC, Cra7yy commented
fix object

2022-08-18 13:25 UTC, Capsonchik commented on src/components/creatorNetwork/creator-network.jsx
> +import {Course} from "./course/course";
codestyle

2022-08-18 13:28 UTC, Capsonchik commented on src/components/creatorNetwork/creator-network.jsx
>    const perecklPlus = () => {
stepUp

2022-08-18 13:28 UTC, Capsonchik commented on src/components/creatorNetwork/creator-network.jsx
>    const precklMinus = () => {
stepDown

2022-08-18 13:28 UTC, Capsonchik commented on src/components/creatorNetwork/creator-network.jsx
> -  const [ vicupPrice, setVicupPrice] = useState('')
currentPrice

2022-08-18 13:37 UTC, Capsonchik requested changes
Хуйня переделывай =)))

2022-08-18 18:59 UTC, merged